//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Quotations2Entities1 : DbContext
    {
        public Quotations2Entities1()
            : base("name=Quotations2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<itemimg> itemimg { get; set; }
        public virtual DbSet<ProductPrice> ProductPrice { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual ObjectResult<Product_cRud_Result> Product_cRud(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("Productid", productid) :
                new ObjectParameter("Productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product_cRud_Result>("Product_cRud", productidParameter);
        }
    
        public virtual int Deletemul_images(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("Productid", productid) :
                new ObjectParameter("Productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Deletemul_images", productidParameter);
        }
    
        public virtual ObjectResult<Item_Rec_Mod_Result> Item_Rec_Mod(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("Productid", productid) :
                new ObjectParameter("Productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Item_Rec_Mod_Result>("Item_Rec_Mod", productidParameter);
        }
    
        public virtual ObjectResult<StartDate_Lead_Result> StartDate_Lead(Nullable<int> product)
        {
            var productParameter = product.HasValue ?
                new ObjectParameter("product", product) :
                new ObjectParameter("product", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StartDate_Lead_Result>("StartDate_Lead", productParameter);
        }
    }
}
